word_list = [
    'abruptly',
    'blizzard',
    'crypt',
    'dwarves',
    'fixable',
    'galaxy',
    'jumbo',
    'puppy',
    'walkway',
    'zombie',
    'absurd',
    'beekeeper',
    'buffalo',
    'wristwatch',
    'buffoon',
    'buzzwords',
    'espionage',
    'keyhole',
    'microwave',
    'nightclub',
    'stretch',
    'witchcraft',
    'pizza',
    'taco', ]
